### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rule_name'

### ISSUE THREAD

**Issue by huyuanzhi2** [LoRexxar/Kunlun-M#183]
win11 python 3.8.5
运行python kunlun.py scan -t ./tests/vulnerabilities/ 出错
 [09:38:43] Traceback (most recent call last):
  File "E:\CodeReviewTools\Kunlun-M\core\__init__.py", line 303, in main
    cli.start(args.target, args.format, args.output, args.special_rules, sid, args.language, args.tamper_name, args.black_path, args.unconfirm, args.unprecom)
  File "E:\CodeReviewTools\Kunlun-M\core\cli.py", line 251, in start
    display_result(task_id)
  File "E:\CodeReviewTools\Kunlun-M\core\cli.py", line 127, in display_result
    rule_name = rule.rule_name
AttributeError: 'NoneType' object has no attribute 'rule_name'

**Comment by huyuanzhi2** [comment]
用kali测了下也是这个错误

**Comment by LoRexxar** [comment]
噢，是不是没有load rules...我忽然发现我好像没在文档里写这个

**Comment by LoRexxar** [comment]
python3 kunlun.py config load

**Comment by huyuanzhi2** [comment]
还真是 多谢大哥

**Comment by huyuanzhi2** [comment]
我石乐志了
