### ISSUE TITLE
安装依赖时候出现这种错误

### ISSUE THREAD

**Issue by dm116** [LoRexxar/Kunlun-M#205]
```
ERROR: Command errored out with exit status 1:
 command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0]]
 = '"'"'/tmp/pip-install-4v3x15oo/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp//
pip-install-4v3x15oo/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'""
', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close())
;exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-inss
tall-4v3x15oo/mysqlclient/pip-egg-info
         cwd: /tmp/pip-install-4v3x15oo/mysqlclient/
    Complete output (15 lines):
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4v3x15oo/mysqlclient/setup.py", line 15, in <modulee
>
        metadata, options = get_config()
      File "/tmp/pip-install-4v3x15oo/mysqlclient/setup_posix.py", line 70, in gg
et_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-4v3x15oo/mysqlclient/setup_posix.py", line 31, in mm
ysql_config
        raise OSError("{} not found".format(_mysql_config_path))
"log" 21L, 1458C                                              1,5           Top
```

**Comment by LoRexxar** [comment]
你这个是装mysqlclient导致的，装这个需要你本地先有mysql的环境，你可以去查查。
也可以不装这个用sqlite就行
