### ISSUE TITLE
TypeError: unhashable type: 'BinaryOp'

### ISSUE THREAD

**Issue by p7e4** [LoRexxar/Kunlun-M#213]
### Python Environment
Python 3.8

### Description
``` php
<?php
define( __NAMESPACE__ . "1", __NAMESPACE__ . "2");

```

``` bash
 [05:42:14] [AST][Pretreatment] new define BinaryOp('.', MagicConstant('__NAMESPACE__', None), '1')=BinaryOp('.', MagicConstant('__NAMESPACE__', None), '2')
 [05:42:14] Traceback (most recent call last):
  File "/root/kunlun/core/__init__.py", line 303, in main
    cli.start(args.target, args.format, args.output, args.special_rules, sid, args.language, args.tamper_name, args.black_path, args.unconfirm, args.unprecom)
  File "/root/kunlun/core/cli.py", line 252, in start
    ast_object.pre_ast_all(main_language, is_unprecom=is_unprecom)
  File "/root/kunlun/core/pretreatment.py", line 90, in pre_ast_all
    loop.run_until_complete(asyncio.gather(*scan_list))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/kunlun/core/pretreatment.py", line 152, in pre_ast
    self.define_dict[key] = define_params[1].node
TypeError: unhashable type: 'BinaryOp'
```

**Comment by LoRexxar** [comment]
看上去是这个语法套娃的问题

**Comment by LoRexxar** [comment]
fix in 2.7.0
