### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rule_name'

### ISSUE THREAD

**Issue by shmilylty** [LoRexxar/Kunlun-M#222]
最新仓库代码 Python 3.10
 [11:35:52] Traceback (most recent call last):
  File "D:\Tools\Kunlun-M\core\__init__.py", line 312, in main
    cli.start(args.target, args.format, args.output, args.special_rules, sid, args.language, args.tamper_name, args.black_path, args.unconfirm, args.unprecom)
  File "D:\Tools\Kunlun-M\core\cli.py", line 261, in start
    display_result(task_id)
  File "D:\Tools\Kunlun-M\core\cli.py", line 128, in display_result
    rule_name = rule.rule_name
AttributeError: 'NoneType' object has no attribute 'rule_name'

**Comment by LoRexxar** [comment]
这个报错是因为在扫描前没有执行

python kunlun.py config load

后续考虑更新这个提示
