### ISSUE TITLE
扫描报错 AttributeError: 'NoneType' object has no attribute 'rule_name'

### ISSUE THREAD

**Issue by nullNullNone** [LoRexxar/Kunlun-M#233]
AttributeError: 'NoneType' object has no attribute 'rule_name'

[02:28:08] Traceback (most recent call last):
  File "/opt/tool/Kunlun-M/core/__init__.py", line 312, in main
    cli.start(args.target, args.format, args.output, args.special_rules, sid, args.language, args.tamper_name, args.black_path, args.unconfirm, args.unprecom)
  File "/opt/tool/Kunlun-M/core/cli.py", line 261, in start
    display_result(task_id)
  File "/opt/tool/Kunlun-M/core/cli.py", line 128, in display_result
    rule_name = rule.rule_name
AttributeError: 'NoneType' object has no attribute 'rule_name'

**Comment by LoRexxar** [comment]
你的报错太简单了，我无法判断问题在哪。

简单的判断感觉是因为你没有初始化规则，在使用之前你需要初始化规则才行
